### ISSUE TITLE
Re-order Dynmap worlds so that Overworld is on top

### ISSUE THREAD

**Issue by sandalle** [mechaet/ModderationConfigs#29]
Re-order [Dynmap](http://playmodd.moretoast.com:8123/) in dynmap/forgeworlds.yml so that the main worlds are listed first. For the current Dynmap world list, mainly Overworld should be moved to the top. :)

e.g. reordered (incomplete, does not list RFTools/AE2 dimensions)

```
worlds:
-   sealevel: 64
    nether: false
    name: world
    the_end: false
    title: world/Overworld
    height: 256
-   sealevel: 64
    nether: false
    name: mining
    the_end: false
    title: mining/Overworld
    height: 256
-   sealevel: 64
    nether: true
    name: DIM-1
    the_end: false
    title: DIM-1/Nether
    height: 256
-   sealevel: 64
    nether: false
    name: DIM-42
    the_end: false
    title: DIM-42/The Outer Lands
    height: 256
-   sealevel: 64
    nether: false
    name: DIM-100
    the_end: false
    title: DIM-100/Underdark
    height: 256
-   sealevel: 64
    nether: false
    name: DIM1
    the_end: true
    title: DIM1/The End
    height: 256
-   sealevel: 64
    nether: false
    name: DIM-47
    the_end: false
    title: DIM-47/Bedrock
    height: 256
-   sealevel: 64
    nether: false
    name: DIM-112
    the_end: false
    title: DIM-112/The Last Millenium
    height: 256
```
